'use strict';
let catalog, current, saved=[];
const $=id=>document.getElementById(id), form=$('form');
const field=n=>form.elements.namedItem(n);
const status=(s,error=false)=>{$('status').textContent=s;$('status').className=error?'error':'';};
function readSaved(){try{const a=JSON.parse(localStorage.getItem('technotes.dependencies.v4')||'[]');saved=Array.isArray(a)?a.filter(validEntry):[];}catch{saved=[];}}
function validEntry(d){return d&&typeof d.label==='string'&&d.label.length<=80&&typeof d.coords==='string'&&/^[A-Za-z0-9_.-]+:[A-Za-z0-9_.-]+(?::[A-Za-z0-9_.+-]*)?(?::(?:compile|provided|runtime|test))?$/.test(d.coords);}
function persist(){try{localStorage.setItem('technotes.dependencies.v4',JSON.stringify(saved));}catch{status('Browser storage unavailable. Export your catalog before closing.',true);}renderSaved();}
function renderSaved(){const host=$('saved');host.replaceChildren();saved.forEach((d,i)=>{const row=document.createElement('div');row.className='saved-row';const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.dataset.custom=d.coords;label.append(input,document.createTextNode(d.label+' · '+d.coords));const remove=document.createElement('button');remove.type='button';remove.textContent='Remove';remove.onclick=()=>{saved.splice(i,1);persist();};row.append(label,remove);host.append(row);});}
function selectPreset(id){current=catalog.presets.find(p=>p.id===id);field('artifactId').value=current.artifact;field('name').value=current.artifact;field('packageName').value=current.pkg;field('groupId').value='com.technotes';field('serverPort').value=current.port;field('serverPort').readOnly=id==='oauth';field('javaVersion').value=catalog.java;const required=current.deps.split(',');document.querySelectorAll('[data-dep]').forEach(c=>{c.checked=required.includes(c.dataset.dep);c.disabled=c.checked;c.parentElement.querySelector('small').textContent=c.checked?'REQUIRED':'';});document.querySelectorAll('[data-preset]').forEach(b=>{b.classList.toggle('active',b.dataset.preset===id);b.setAttribute('aria-pressed',String(b.dataset.preset===id));});$('note').textContent=current.note;status('');updateSummary();}
function updateSummary(){$('summaryName').textContent=field('artifactId').value;$('summaryPkg').textContent=field('packageName').value;$('count').textContent=document.querySelectorAll('[data-dep]:checked').length;}
function requestBody(){const body=new URLSearchParams(new FormData(form));body.set('preset',current.id);body.set('deps',[...document.querySelectorAll('[data-dep]:checked')].map(c=>c.dataset.dep).join(','));const selected=[...document.querySelectorAll('[data-custom]:checked')].map(c=>c.dataset.custom);body.set('customDeps',[...new Set([...selected,...$('extras').value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)])].join('\n'));return body;}
async function generate(preview){if(!form.reportValidity())return;status(preview?'Preparing POM preview…':'Generating project…');$('generate').disabled=$('preview').disabled=true;try{const r=await fetch(preview?'/preview':'/generate',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:requestBody()});if(!r.ok)throw new Error(await r.text());if(preview){$('pom').textContent=await r.text();$('previewPanel').hidden=false;$('previewPanel').scrollIntoView({behavior:'smooth'});status('POM preview ready.');}else{download(await r.blob(),field('artifactId').value+'.zip');status('ZIP generated. Extract it into a new folder and open pom.xml in IntelliJ.');}}catch(e){status(e.message,true);}finally{$('generate').disabled=$('preview').disabled=false;}}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
form.addEventListener('submit',e=>{e.preventDefault();generate(false);});form.addEventListener('input',updateSummary);
$('preview').onclick=()=>generate(true);$('closePreview').onclick=()=>{$('previewPanel').hidden=true;};
$('search').oninput=()=>{const q=$('search').value.toLowerCase();document.querySelectorAll('.dep').forEach(d=>d.hidden=!d.textContent.toLowerCase().includes(q));};
$('saveDep').onclick=()=>{const d={label:$('depLabel').value.trim(),coords:$('depCoords').value.trim()};if(!d.label||!validEntry(d)){status('Enter a display name and valid Maven coordinates.',true);return;}if(saved.some(x=>x.coords===d.coords)){status('This dependency is already saved.',true);return;}saved.push(d);persist();status('Dependency saved in this browser.');};
$('export').onclick=()=>download(new Blob([JSON.stringify(saved,null,2)],{type:'application/json'}),'technotes-dependencies.json');
$('import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>32768)throw new Error('Catalog is too large (maximum 32 KB).');const t=await f.text();const rows=f.name.endsWith('.tsv')?t.split(/\r?\n/).filter(x=>x.trim()&&!x.startsWith('#')).map(x=>{const [label,coords]=x.split('\t');return {label,coords};}):JSON.parse(t);if(!Array.isArray(rows)||rows.length>100||!rows.every(validEntry))throw new Error('Invalid catalog format.');for(const d of rows)if(!saved.some(x=>x.coords===d.coords))saved.push(d);persist();status('Catalog imported.');}catch(err){status(err.message,true);}finally{e.target.value='';}};
(async()=>{try{const r=await fetch('/api/catalog');if(!r.ok)throw new Error('Could not load catalog');catalog=await r.json();$('versions').replaceChildren();for(const t of ['JAVA '+catalog.java,'SPRING BOOT '+catalog.boot,'CLOUD '+catalog.cloud]){const span=document.createElement('span');span.className='badge';span.textContent=t;$('versions').append(span);}catalog.presets.forEach(p=>{const b=document.createElement('button');b.type='button';b.className='preset';b.dataset.preset=p.id;b.textContent=p.label;b.onclick=()=>selectPreset(p.id);$('presets').append(b);});catalog.dependencies.forEach(d=>{const label=document.createElement('label');label.className='dep';const c=document.createElement('input');c.type='checkbox';c.dataset.dep=d.id;const small=document.createElement('small');label.append(c,document.createTextNode(d.label),small);$('dependencies').append(label);});readSaved();renderSaved();selectPreset('oauth');}catch(e){status(e.message,true);$('generate').disabled=$('preview').disabled=true;}})();
